---
- name: Playbook to launch customize-ssh-keys.yml
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Include vars
      include_vars:
        file: vars/main.yml

    - name: Include tasks from customize-ssh-keys.yml
      ansible.builtin.include_tasks: customize-ssh-keys.yml