---
- name: Playbook to launch customize-ssh-keys.yml
  hosts: axinecidm01.ecommerce.inditex.grp
  gather_facts: false
  tasks:
    - name: Include vars
      include_vars:
        file: vars/main.yml

    - name: Include tasks from customize-ssh-keys.yml
      ansible.builtin.include_tasks: customize-ssh-keys.yml